# This GitHub Action checks if a pull request targeting the master branch
# has one of the specified "DO NOT MERGE" labels, and if it does,
# it will block the merge by failing the action

name: Get latest translation files

on:
  schedule:
    - cron: '0 9 * * fri'

  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  makeRequest:
    runs-on: ubuntu-latest

    steps:
    - name: Make request to external URI
      run: |
        curl -X POST \
        -H "X-Api-Token: 5e86a1b0e369a745c1f82b72360b8dfa9ad29ced" \
        -H "accept: application/json" \
        -H "content-type: application/json" \
        -d '{
          "format": "json",
          "filter_data": ["translated","reviewed","verified"],
          "filter_langs": ["fr","de","es"],
          "filter_repositories":["NintexGlobal/pi-processmodeler/tree/lokalise/test1/packages/pi-bpmn-canvas:lokalise/test1"],
          "directory_prefix": "",
          "original_filenames": true,
          "commit_message": "fix: updated languages via api call",
          "triggers": [
          "github"
        ]}' \
        https://api.lokalise.com/api2/projects/5819839665c325a2af9ab2.19829574/files/download
